/**
 * A character built out of the real SRD, for tests that mount a screen.
 *
 * `tests/fixtures/factories.ts` invents its dataset on purpose - the engine
 * tests are about arithmetic and want a shape they control. A screen is the
 * other case: it renders names, card text, domain marks and weapon features
 * that only exist in the shipped dataset, and a synthetic dataset would let a
 * render path that crashes on real content pass.
 *
 * So this reaches for `baseDataset`, which is the JSON compiled into the
 * bundle, and picks the first thing of each kind that resolves. Nothing here
 * is a fixed id: the SRD is regenerated by `tools/build-srd.ts`, and a fixture
 * pinned to `wizard-school-of-knowledge` would rot the first time it moves.
 */
import type { Character, DomainCard } from '@shared/types.ts';
import { deriveStats, indexDataset, newCharacter } from '@engine/character.ts';
import { baseDataset } from '../../src/store/dataset.ts';

export const dataset = baseDataset;
export const index = indexDataset(baseDataset);

/**
 * A character that has actually been played: levelled, geared, with cards in
 * both loadout and vault, damage taken and an Experience named.
 *
 * The empty sheet is the easy case. Most render paths in this app only exist
 * once something is on them - a threshold row, a recall cost, a scar.
 */
export function playedCharacter(): Character {
  const klass = dataset.classes[0]!;
  const subclass = dataset.subclasses.find((s) => s.classRef === klass.id)!;
  const inDomain = (level: number): DomainCard[] =>
    dataset.domainCards.filter((c) => klass.domains.includes(c.domain) && c.level <= level);
  const cards = inDomain(3);
  const weapon = dataset.weapons.find((w) => w.slot === 'primary' && w.tier === 1)!;
  const secondary = dataset.weapons.find((w) => w.slot === 'secondary' && w.tier === 1);
  const armor = dataset.armors.find((a) => a.tier === 1)!;

  const c = newCharacter({
    name: 'Fixture',
    pronouns: 'they/them',
    classRef: klass.id,
    subclassRefs: [subclass.id],
    ancestryRefs: dataset.ancestries[0] ? [dataset.ancestries[0].id] : [],
    communityRef: dataset.communities[0]?.id ?? null,
    level: 3,
    traits: { agility: 1, strength: 2, finesse: 0, instinct: 1, presence: 0, knowledge: -1 },
    loadout: cards.slice(0, 3).map((c2) => c2.id),
    vault: cards.slice(3, 6).map((c2) => c2.id),
    activePrimaryWeapon: weapon.id,
    activeSecondaryWeapon: secondary?.id ?? null,
    activeArmor: armor.id,
    inventory: [
      { ref: dataset.consumables[0]?.id ?? null, name: 'Minor Health Potion', quantity: 2, note: 'Clears 1d4 HP.' },
      { ref: null, name: 'A rope, forty feet', quantity: 1 },
    ],
    experiences: [
      { id: 'exp-1', name: 'Ran with the wolves', bonus: 2 },
      // The unnamed one is deliberate: creation used to filter these out, and
      // an unnamed Experience is still worth +2 and still armable.
      { id: 'exp-2', name: '', bonus: 2 },
    ],
    gold: { handfuls: 4, bags: 1, chests: 0 },
    connections: ['Owes the innkeeper an apology'],
    notes: 'Notes that reach the sheet.',
    scars: ['A ledger of names'],
  });

  const stats = deriveStats(c, dataset, index);
  return {
    ...c,
    hp: { marked: 2, max: stats.maxHp },
    stress: { marked: 3, max: stats.maxStress },
    hope: { marked: 4, max: stats.maxHope },
    armorSlots: { marked: 1, max: stats.armorScore },
  };
}

export const playedStats = (c: Character = playedCharacter()) => deriveStats(c, dataset, index);
