/**
 * The campaign schema, held to the same policy as the character one.
 *
 * Architecture 6.1 is one rule - "no schema ships without its converter" - and
 * campaigns are the first record in this app to be governed by it that is not
 * a `Character`. The temptation was to write a second, softer policy for a
 * store nobody has data in yet. That is exactly backwards: today is the only
 * day the enforcement is free, because on the day of the first bump every
 * campaign in the world is already on somebody's phone.
 *
 * So this file asks of `CAMPAIGN_SCHEMA_VERSION` precisely what
 * `tests/store/migrations.test.ts` asks of `SCHEMA_VERSION`:
 *
 *   - no gap in the chain between the oldest readable version and this one;
 *   - a committed fixture per readable version, written by the build that
 *     shipped it and never regenerated by a later one;
 *   - every fixture still reads into a campaign at the current schema, with
 *     the fields a GM would notice still in it.
 *
 * Plus the two things the character policy does not have to worry about,
 * because a character has no list of heterogeneous rows in it: an item this
 * build cannot read is kept rather than dropped, and a link that points at
 * something unrecognised is still a link.
 *
 * ## And, since 2026-08-18, the first bump
 *
 * `CAMPAIGN_SCHEMA_VERSION` moved to 2, and the converter for it changes no
 * field on purpose: the number moved so that *older* builds refuse a record
 * carrying a `url` or a `note` row, not because anything in a v1 record is
 * wrong. That claim is only worth making if it is checked, so the last describe
 * here walks the frozen v1 fixture forward and requires it back deep-equal
 * apart from the stamp *and* byte-identical under `JSON.stringify`, which is
 * the comparison the `.dhcampaign` checksum actually makes. A converter that
 * quietly dropped a field, or reordered the keys, or renamed
 * one, or normalised a countdown on the way through would fail it - which is
 * the whole point of writing a converter that does nothing and saying so.
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import {
  CAMPAIGN_MIGRATIONS,
  CAMPAIGN_SCHEMA_VERSION,
  CampaignReadError,
  countdownsIn,
  countdownsOf,
  emptyBoard,
  liveScenes,
  migrateCampaignRecord,
  newCampaign,
  OLDEST_READABLE_CAMPAIGN,
  GM_REGIONS,
  primaryCountdownOf,
  readCampaignRecord,
  withPrimaryCountdown,
  withSceneScope,
  type Campaign,
  type SessionItem,
} from '../../shared/campaigns.ts';
import {
  applyChain,
  missingConverters,
  readableVersions,
  SchemaError,
} from '../../shared/migrations.ts';
import { MAX_FEAR, SCHEMA_VERSION, type SceneCombatant } from '../../shared/types.ts';
import { newCharacter } from '../../src/engine/character.ts';

const FIXTURES = fileURLToPath(new URL('../fixtures/schema', import.meta.url));

const readFixture = (version: number): Record<string, unknown> =>
  JSON.parse(readFileSync(join(FIXTURES, `v${version}.campaign.json`), 'utf8')) as Record<
    string,
    unknown
  >;

const versions = (): number[] =>
  readableVersions(OLDEST_READABLE_CAMPAIGN, CAMPAIGN_SCHEMA_VERSION);

/** A minimal record: only what `readCampaignRecord` genuinely insists on. */
const bare = (patch: Record<string, unknown> = {}): Record<string, unknown> => ({
  id: 'campaign-1',
  schemaVersion: CAMPAIGN_SCHEMA_VERSION,
  name: 'A Campaign',
  ...patch,
});

describe('the policy, applied to a second schema', () => {
  it('numbers campaigns separately from characters, on purpose', () => {
    // Not an accident of ordering: folding campaigns into SCHEMA_VERSION would
    // make every future campaign change a character migration, and force every
    // committed character fixture to be rewritten for a field no character has.
    expect(CAMPAIGN_SCHEMA_VERSION).not.toBe(SCHEMA_VERSION);
  });

  it('has a converter for every step from the oldest readable version to this one', () => {
    const gaps = missingConverters(
      OLDEST_READABLE_CAMPAIGN,
      CAMPAIGN_SCHEMA_VERSION,
      CAMPAIGN_MIGRATIONS,
    );
    expect(
      gaps,
      `campaign schema ${gaps.join(', ')} can be read by no converter in shared/campaigns.ts.`,
    ).toEqual([]);
  });

  it('would fail on a bump that shipped without its converter', () => {
    // The teeth, without touching the constant. If this ever comes back empty
    // the check above has gone vacuous - passing because the range is empty
    // rather than because it is covered.
    expect(
      missingConverters(
        CAMPAIGN_SCHEMA_VERSION,
        CAMPAIGN_SCHEMA_VERSION + 1,
        CAMPAIGN_MIGRATIONS,
      ),
    ).toEqual([CAMPAIGN_SCHEMA_VERSION]);
  });

  it('carries no converter for a version this build has not left yet', () => {
    const ahead = CAMPAIGN_MIGRATIONS.filter((m) => m.from >= CAMPAIGN_SCHEMA_VERSION);
    expect(ahead.map((m) => m.from)).toEqual([]);
  });

  it('gives every converter a line of changelog', () => {
    for (const m of CAMPAIGN_MIGRATIONS) {
      expect(m.note.trim().length, `campaign schema ${m.from}`).toBeGreaterThan(0);
    }
  });
});

describe('the committed fixtures', () => {
  it('has one per readable version', () => {
    for (const version of versions()) {
      expect(() => readFixture(version), `no committed fixture for campaign v${version}`).not.toThrow();
    }
  });

  it('keeps each fixture at the version its name claims', () => {
    // A fixture rewritten by a later build proves only that the current code
    // can read its own output, which is not the question being asked.
    for (const version of versions()) {
      expect(readFixture(version)['schemaVersion'], `v${version}.campaign.json`).toBe(version);
    }
  });

  for (const version of versions()) {
    it(`still opens the campaign schema ${version} record whole`, () => {
      const { campaign, warnings } = readCampaignRecord(readFixture(version));

      /*
       * One warning, and it is the party row.
       *
       * Every committed fixture carries the same nine-field stand-in where a
       * character should be - `armorSlots`, `hope`, `hp`, `id`, `level`, `name`,
       * `pronouns`, `schemaVersion`, `stress` - which was enough to store and
       * never enough to draw. `readPartyMember` refuses it now, so this walk
       * expects the refusal rather than silence. The fixtures are NOT
       * regenerated to make it go away: a fixture rewritten by a later build
       * proves only that the current code can read its own output, which is the
       * rule this whole file exists to keep.
       */
      expect(warnings).toHaveLength(1);
      expect(warnings[0]).toMatch(/not a whole character/);
      expect(campaign.schemaVersion).toBe(CAMPAIGN_SCHEMA_VERSION);

      // Not just "it parsed". These are the things a GM would notice missing.
      expect(campaign.name).toBe('The Sablewood Winter');
      expect(campaign.fear).toBe(7);
      /*
       * The five rows every fixture has carried since v1, in the order they
       * were written, at the front of the list.
       *
       * `slice` rather than the whole array because a later fixture is the
       * same table with the rows that schema added on the end - v2 has a `url`
       * and a `note` after these - and pinning the whole list would mean the
       * bump rewriting this assertion, which is the one thing a frozen fixture
       * exists to stop. It is still exact about these five: a fixture that lost
       * one, reordered two, or read a `link` as `unreadable` fails here, because
       * `slice(0, 5)` of a shorter list is shorter and `toEqual` is not a
       * prefix match.
       */
      expect(campaign.session.slice(0, 5).map((i) => i.kind)).toEqual([
        'scene',
        'encounter',
        'countdown',
        'link',
        'link',
      ]);
      expect(campaign.board.environmentRef).toBe('raging-river');
      // The row is gone, and the sentence that took it away names the
      // character, which is the only part of a refusal a GM can act on.
      expect(campaign.party).toEqual([]);
      expect(warnings[0]).toContain('Ilya of the Ninth');

      const fight = campaign.session.find((i) => i.kind === 'encounter');
      expect(fight?.kind === 'encounter' && fight.roster).toHaveLength(2);
      expect(fight?.kind === 'encounter' && fight.combatants[0]?.hp.marked).toBe(3);

      expect(primaryCountdownOf(campaign.session)?.value).toBe(4);
    });
  }

  it('opens the schema 4 record with both of its pointers standing', () => {
    /*
     * Said here rather than in the loop above, because v1, v2 and v3 have
     * neither field and asserting on them would only prove that the reader
     * supplies a default.
     *
     * This is what the bump bought: a fight parked in the row it came from,
     * and a clock that belongs to one scene rather than to the evening. A
     * reader that dropped either would still pass every assertion above.
     */
    const { campaign, warnings } = readCampaignRecord(readFixture(4));

    expect(campaign.board.liveScene).toBe('item-scene-1');
    expect(campaign.session.some((i) => i.id === 'item-scene-1')).toBe(true);

    const thaw = campaign.session.find((i) => i.id === 'item-countdown-2');
    expect(thaw?.kind === 'countdown' && thaw.sceneId).toBe('item-scene-1');
    expect(thaw?.kind === 'countdown' && thaw.primary).toBe(false);

    // The clock that was already here keeps its pin, and keeps being the
    // campaign's: a scope on one row does not reach the others.
    const ice = campaign.session.find((i) => i.id === 'item-countdown-1');
    expect(ice?.kind === 'countdown' && ice.sceneId).toBe(null);
    expect(primaryCountdownOf(campaign.session)?.id).toBe('item-countdown-1');

    // Still the one party warning, and no repair fired: nothing in this
    // fixture is dangling, so the pass must be silent on it.
    expect(warnings).toHaveLength(1);
  });
});

describe('a campaign owns its own things, and not the player characters', () => {
  it('holds a name, a session list, Fear, countdowns and a party', () => {
    const c = newCampaign('Ashes of Rivermarch', '2026-08-16T10:00:00.000Z', 'campaign-1');
    expect(c.name).toBe('Ashes of Rivermarch');
    expect(c.session).toEqual([]);
    expect(c.fear).toBe(0);
    expect(c.party).toEqual([]);
    expect(c.board).toEqual(emptyBoard());
  });

  it('stamps itself with the campaign schema, never the character one', () => {
    const c = newCampaign('x', '2026-08-16T10:00:00.000Z', 'campaign-1');
    expect(c.schemaVersion).toBe(CAMPAIGN_SCHEMA_VERSION);
  });
});

describe('the two refusals, and nothing else', () => {
  it('will not read a record a newer build wrote, and says to update the app', () => {
    expect(() =>
      readCampaignRecord(bare({ schemaVersion: CAMPAIGN_SCHEMA_VERSION + 1 })),
    ).toThrow(SchemaError);
    expect(() =>
      readCampaignRecord(bare({ schemaVersion: CAMPAIGN_SCHEMA_VERSION + 1 })),
    ).toThrow(/newer version of the app.*Update the app/s);
  });

  it('will not read a record with no id, because there is nothing to write back to', () => {
    // Inventing one here is how a campaign gets duplicated on every launch.
    const { id, ...rest } = bare();
    expect(id).toBeDefined();
    expect(() => readCampaignRecord(rest)).toThrow(CampaignReadError);
    expect(() => readCampaignRecord(rest)).toThrow(/nothing to write it back to/);
  });

  it('opens a record that is otherwise almost empty', () => {
    const { campaign } = readCampaignRecord(bare());
    expect(campaign.name).toBe('A Campaign');
    expect(campaign.session).toEqual([]);
    expect(campaign.board.region).toBe('encounter');
    expect(campaign.board.partyTier).toBe(1);
  });

  it('reads a record with no stamp as this build’s, the way a hand-edited file arrives', () => {
    const { schemaVersion, ...rest } = bare();
    expect(schemaVersion).toBe(CAMPAIGN_SCHEMA_VERSION);
    expect(readCampaignRecord(rest).campaign.schemaVersion).toBe(CAMPAIGN_SCHEMA_VERSION);
  });

  /*
   * `board.region` is a union in the type and a list in the reader, and only
   * the list is load-bearing on the way in from a disk. Widening one and
   * forgetting the other used to typecheck perfectly and lose the new tool on
   * every single reload - silently, because the fallback is a real region.
   *
   * That hole is closed in the source rather than here: `GM_REGIONS` is the
   * keys of a `Record<GmRegion, true>`, so a region with no entry is a missing
   * property and an entry that is not a region is an excess one. This case can
   * only ever loop the list it is given, which is exactly why it could not hold
   * the hazard its own comment described - it named `'reference'` as "the one
   * added last" and stayed green through two more regions being added after it.
   */
  it('keeps every region this build knows, one at a time', () => {
    for (const region of GM_REGIONS) {
      const { campaign } = readCampaignRecord(bare({ board: { region } }));
      expect(campaign.board.region, `${region} did not survive a read`).toBe(region);
    }
    // Not vacuous: an empty list would pass the loop above in silence.
    expect(GM_REGIONS.length).toBeGreaterThan(1);
  });

  it('falls back for a region no build knows, which is what makes widening safe', () => {
    // The guarantee the reference tab was added on: an older build meeting a
    // newer record forgets which tool was open and loses nothing else.
    const { campaign } = readCampaignRecord(bare({ board: { region: 'holodeck' } }));
    expect(campaign.board.region).toBe('encounter');
  });
});

describe('a session item this build cannot read', () => {
  const withItem = (item: unknown): Campaign =>
    readCampaignRecord(bare({ session: [item] })).campaign;

  it('is kept and named, not dropped', () => {
    // The failure this repo has shipped twice: the list comes back one row
    // shorter and the GM has no way to learn which row it was.
    const kept = withItem({ id: 'i1', kind: 'handout', name: 'The letter' });
    expect(kept.session).toHaveLength(1);
    expect(kept.session[0]!.kind).toBe('unreadable');
    expect(kept.session[0]!.name).toBe('The letter');
  });

  it('says what it was, in a sentence a screen can print', () => {
    const item = withItem({ id: 'i1', kind: 'handout', name: 'The letter' }).session[0]!;
    expect(item.kind === 'unreadable' && item.why).toMatch(/no "handout" item/);
  });

  it('keeps the bytes it arrived as, so nothing is actually lost', () => {
    const item = withItem({ id: 'i1', kind: 'handout', url: 'x', name: '' }).session[0]!;
    expect(item.kind === 'unreadable' && JSON.parse(item.raw)).toMatchObject({
      kind: 'handout',
      url: 'x',
    });
  });

  it('does not wrap an already-wrapped item a second time', () => {
    const once = withItem({ id: 'i1', kind: 'handout', name: 'x' }).session[0]!;
    const twice = withItem(once).session[0]!;
    expect(twice.kind === 'unreadable' && JSON.parse(twice.raw)).toMatchObject({ kind: 'handout' });
  });

  it('warns about it, rather than only recording it', () => {
    const { warnings } = readCampaignRecord(bare({ session: [{ id: 'i1', kind: 'handout' }] }));
    expect(warnings.join(' ')).toMatch(/could not be read/);
  });
});

/*
 * A `link` row, which is still the in-app one.
 *
 * Campaign schema 2 added a `url` row beside it - a different kind, with its own
 * reader and its own six mitigations, exercised in
 * `tests/store/campaignUrlRow.test.ts`. `LINK_KINDS` did not gain a fifth
 * entry, and this describe is about the four that were always there.
 */
describe('a link row, which still never leaves the app', () => {
  const target = (t: unknown): SessionItem =>
    readCampaignRecord(bare({ session: [{ id: 'i1', kind: 'link', name: 'n', target: t }] }))
      .campaign.session[0]!;

  it('reads the four things a link may point at', () => {
    for (const kind of ['adversary', 'environment', 'domainCard', 'rule']) {
      const item = target({ kind, ref: 'r' });
      expect(item.kind === 'link' && item.target.kind).toBe(kind);
    }
  });

  it('keeps a target it does not recognise, and remembers what it called itself', () => {
    const item = target({ kind: 'campaignFrame', ref: 'the-witherwild' });
    expect(item.kind).toBe('link');
    expect(item.kind === 'link' && item.target.kind).toBe('unknown');
    expect(item.kind === 'link' && item.target.kind === 'unknown' && item.target.named).toBe(
      'campaignFrame',
    );
    expect(item.kind === 'link' && item.target.ref).toBe('the-witherwild');
  });

  it('keeps the ref even when there is no kind at all', () => {
    const item = target({ ref: 'the-witherwild' });
    expect(item.kind === 'link' && item.target.ref).toBe('the-witherwild');
  });
});

describe('countdowns, which live in the session list', () => {
  const countdownItem = (id: string, primary: boolean): Record<string, unknown> => ({
    id,
    kind: 'countdown',
    name: id,
    primary,
    countdown: { id, name: id, kind: 'standard', start: 4, value: 2, notes: '' },
  });

  it('collects them in list order', () => {
    const { campaign } = readCampaignRecord(
      bare({ session: [countdownItem('a', false), countdownItem('b', true)] }),
    );
    expect(countdownsOf(campaign.session).map((c) => c.id)).toEqual(['a', 'b']);
  });

  it('lets at most one be the primary one', () => {
    // Two rows both claiming to be the one the GM is watching is not a state
    // any screen can draw honestly, and a hand-edited file can reach it.
    const { campaign, warnings } = readCampaignRecord(
      bare({ session: [countdownItem('a', true), countdownItem('b', true)] }),
    );
    expect(campaign.session.filter((i) => i.kind === 'countdown' && i.primary)).toHaveLength(1);
    expect(primaryCountdownOf(campaign.session)?.id).toBe('a');
    expect(warnings.join(' ')).toMatch(/more than one countdown/);
  });

  it('moves the flag rather than adding a second one', () => {
    const { campaign } = readCampaignRecord(
      bare({ session: [countdownItem('a', true), countdownItem('b', false)] }),
    );
    const moved = withPrimaryCountdown(campaign.session, 'b');
    expect(moved.filter((i) => i.kind === 'countdown' && i.primary).map((i) => i.id)).toEqual(['b']);
  });

  it('clears the flag when told to make a non-countdown primary', () => {
    const { campaign } = readCampaignRecord(bare({ session: [countdownItem('a', true)] }));
    expect(withPrimaryCountdown(campaign.session, null).some((i) => i.kind === 'countdown' && i.primary)).toBe(
      false,
    );
  });

  /*
   * The scope, and the two pointers the reader answers together.
   *
   * `CAMPAIGN_SCHEMA_VERSION` 4. A countdown row may belong to one scene, and
   * the board remembers the row its fight came from. Both name a row by id and
   * both are reachable dangling, so both are repaired in one pass on the way
   * in - never trusted, and never emptied.
   */
  describe('a countdown that belongs to a scene', () => {
    const sceneRow = (id: string): Record<string, unknown> => ({
      id,
      kind: 'scene',
      name: id,
      environmentRef: 'raging-river',
      roster: [],
      adjustments: { easier: false, harder: false, damageBump: false },
      combatants: [],
    });

    const scoped = (id: string, sceneId: string | null, primary = false): Record<string, unknown> => ({
      ...countdownItem(id, primary),
      sceneId,
    });

    it('reads a schema-3 row as the campaign’s, because that is what every one of them was', () => {
      const { campaign, warnings } = readCampaignRecord(
        bare({ session: [countdownItem('a', false)] }),
      );
      const row = campaign.session[0];
      expect(row?.kind === 'countdown' && row.sceneId).toBe(null);
      expect(warnings).toEqual([]);
    });

    it('keeps a scope that names a row this campaign still has', () => {
      const { campaign, warnings } = readCampaignRecord(
        bare({ session: [sceneRow('s1'), scoped('a', 's1')] }),
      );
      const row = campaign.session.find((i) => i.kind === 'countdown');
      expect(row?.kind === 'countdown' && row.sceneId).toBe('s1');
      expect(warnings).toEqual([]);
    });

    it('hands it back to the campaign when its scene is gone, rather than losing the clock', () => {
      // Degrade, never vanish: the same policy `readLinkTarget` applies to a
      // target it does not recognise. A clock nobody can reach is worse than a
      // clock in the wrong place, because only one of the two can be moved.
      const { campaign, warnings } = readCampaignRecord(
        bare({ session: [scoped('a', 'a-row-that-was-deleted')] }),
      );
      const row = campaign.session[0];
      expect(row?.kind === 'countdown' && row.sceneId).toBe(null);
      expect(row?.kind === 'countdown' && row.countdown.id).toBe('a');
      expect(warnings.join(' ')).toMatch(/no longer has/);
    });

    it('keeps a scope that names an unreadable row, because that row keeps its id', () => {
      /*
       * The set is every row's id, not every scene row's. An `unreadable` row
       * keeps its id precisely so a build that cannot parse it still cannot
       * lose it - and nulling a pointer at one, then letting the next save
       * write that back, is how that arm's whole purpose gets defeated.
       */
      const { campaign } = readCampaignRecord(
        bare({
          session: [{ id: 's1', kind: 'photo', blob: 'AAAA' }, scoped('a', 's1')],
        }),
      );
      const row = campaign.session.find((i) => i.kind === 'countdown');
      expect(row?.kind === 'countdown' && row.sceneId).toBe('s1');
    });

    it('clears the pin when a row is both scoped and pinned, because the top bar is the campaign’s', () => {
      const { campaign, warnings } = readCampaignRecord(
        bare({ session: [sceneRow('s1'), scoped('a', 's1', true)] }),
      );
      const row = campaign.session.find((i) => i.kind === 'countdown');
      expect(row?.kind === 'countdown' && row.primary).toBe(false);
      expect(row?.kind === 'countdown' && row.sceneId).toBe('s1');
      expect(primaryCountdownOf(campaign.session)).toBe(null);
      expect(warnings.join(' ')).toMatch(/both pinned to the top bar and given to a scene/);
    });

    it('strips the scoped pin before deduping, so a real pin further down survives', () => {
      /*
       * The order of the two repairs is load-bearing, and getting it backwards
       * destroys the GM's actual pin without a word.
       *
       * The dedupe keeps the FIRST primary row in array order. If it ran on
       * the raw list, the scoped row here would win it, `b` would be cleared
       * as a duplicate, and the scope repair would then clear the scoped one
       * too - leaving zero primary rows and an empty top bar. So: strip the
       * scoped primaries, then dedupe what is left.
       */
      const { campaign } = readCampaignRecord(
        bare({ session: [sceneRow('s1'), scoped('a', 's1', true), countdownItem('b', true)] }),
      );
      expect(primaryCountdownOf(campaign.session)?.id).toBe('b');
    });

    it('refuses to pin one, and says so by clearing rather than by pretending', () => {
      // `withPrimaryCountdown` is total, and this is the second way of being
      // ineligible - the same honest reading as passing an id that is not a
      // countdown at all.
      const { campaign } = readCampaignRecord(
        bare({ session: [sceneRow('s1'), scoped('a', 's1'), countdownItem('b', true)] }),
      );
      const moved = withPrimaryCountdown(campaign.session, 'a');
      expect(moved.some((i) => i.kind === 'countdown' && i.primary)).toBe(false);
    });
  });

  describe('the scene rows a GM is flipping between', () => {
  /*
   * Derived, never stored, and that is the whole of its argument: it cannot go
   * stale, it survives an export for free, and deleting a row takes it off the
   * strip with no cleanup anywhere.
   */
  const sceneRow = (id: string, combatants: unknown[] = []): Record<string, unknown> => ({
    id,
    kind: 'scene',
    name: id,
    environmentRef: null,
    roster: [],
    adjustments: { easier: false, harder: false, damageBump: false },
    combatants,
  });

  const fighter = {
    id: 'acid-burrower-0',
    adversaryRef: 'acid-burrower',
    name: 'Acid Burrower',
    hp: { max: 8, marked: 2 },
    stress: { max: 3, marked: 0 },
    thresholds: [8, 15],
    difficulty: 14,
    spotlighted: false,
    notes: '',
  };

  it('counts a row live because it holds a fight, or because it is the one on the board', () => {
    const { campaign } = readCampaignRecord(
      bare({ session: [sceneRow('a', [fighter]), sceneRow('b'), sceneRow('c')] }),
    );
    expect(liveScenes(campaign.session, 'b').map((i) => i.id)).toEqual(['a', 'b']);
  });

  it('leaves a planned-and-never-fought row off it', () => {
    const { campaign } = readCampaignRecord(bare({ session: [sceneRow('a'), sceneRow('b')] }));
    expect(liveScenes(campaign.session, null)).toEqual([]);
  });

  it('never puts a legacy encounter row on it, whatever it is holding', () => {
    /*
     * That arm has no `environmentRef`, so resuming one would open the fight in
     * the PREVIOUS scene's place - textually the defect the scene row absorbed
     * the fight to close. It is also the arm nothing can mint any more.
     */
    const { campaign } = readCampaignRecord(
      bare({
        session: [
          {
            id: 'legacy',
            kind: 'encounter',
            name: 'legacy',
            roster: [],
            adjustments: { easier: false, harder: false, damageBump: false },
            combatants: [fighter],
          },
        ],
      }),
    );
    expect(campaign.session[0]?.kind).toBe('encounter');
    expect(liveScenes(campaign.session, 'legacy')).toEqual([]);
  });

  it('keeps them in list order rather than by when they were last played', () => {
    // A strip that reorders under a thumb is the one thing muscle memory
    // cannot use.
    const { campaign } = readCampaignRecord(
      bare({ session: [sceneRow('a', [fighter]), sceneRow('b', [fighter])] }),
    );
    expect(liveScenes(campaign.session, 'b').map((i) => i.id)).toEqual(['a', 'b']);
  });
});

describe('the row the fight on the board came from', () => {
    const sceneRow = (id: string): Record<string, unknown> => ({
      id,
      kind: 'scene',
      name: id,
      environmentRef: null,
      roster: [],
      adjustments: { easier: false, harder: false, damageBump: false },
      combatants: [],
    });

    it('starts at nothing, because a fresh board came from nowhere', () => {
      expect(emptyBoard().liveScene).toBe(null);
    });

    it('reads a schema-3 board as belonging to no row', () => {
      const { campaign, warnings } = readCampaignRecord(bare());
      expect(campaign.board.liveScene).toBe(null);
      expect(warnings).toEqual([]);
    });

    it('keeps a pointer to a row this campaign still has', () => {
      const { campaign, warnings } = readCampaignRecord(
        bare({ session: [sceneRow('s1')], board: { liveScene: 's1' } }),
      );
      expect(campaign.board.liveScene).toBe('s1');
      expect(warnings).toEqual([]);
    });

    it('lets the fight belong to no row when its row is gone, and does not empty the board', () => {
      // The GM is playing that fight. Losing it because the plan row behind it
      // was deleted is the silent loss this pass exists to refuse; it gets a
      // home again the next time a scene is run.
      const { campaign, warnings } = readCampaignRecord(
        bare({ session: [sceneRow('s1')], board: { liveScene: 'a-row-that-was-deleted' } }),
      );
      expect(campaign.board.liveScene).toBe(null);
      expect(warnings.join(' ')).toMatch(/came from a scene this campaign no longer has/);
    });

    it('says nothing when there was no pointer to repair', () => {
      // A warning that fires on an ordinary launch is a warning that stops
      // being read, which is `readSessionItem`'s argument about empty rows.
      const { warnings } = readCampaignRecord(bare({ board: { liveScene: null } }));
      expect(warnings).toEqual([]);
    });
  });

  it('brings a countdown value back inside its own start', () => {
    const { campaign } = readCampaignRecord(
      bare({
        session: [
          {
            id: 'a',
            kind: 'countdown',
            name: 'a',
            primary: false,
            countdown: { id: 'a', name: 'a', kind: 'standard', start: 4, value: 99, notes: '' },
          },
        ],
      }),
    );
    expect(countdownsOf(campaign.session)[0]!.value).toBe(4);
  });
});

describe('the repairs, which never cost the record', () => {
  it('brings a Fear pool from outside the ladder back onto it, and says so', () => {
    const { campaign, warnings } = readCampaignRecord(bare({ fear: 99 }));
    expect(campaign.fear).toBe(MAX_FEAR);
    expect(warnings.join(' ')).toMatch(/Fear pool held 99/);
  });

  it('re-numbers the order so a list written without one keeps its order', () => {
    const { campaign } = readCampaignRecord(
      bare({
        session: [
          { id: 'a', kind: 'scene', name: 'a' },
          { id: 'b', kind: 'scene', name: 'b' },
          { id: 'c', kind: 'scene', name: 'c' },
        ],
      }),
    );
    expect(campaign.session.map((i) => i.id)).toEqual(['a', 'b', 'c']);
    expect(campaign.session.map((i) => i.order)).toEqual([0, 1, 2]);
  });

  it('sorts by the order it was given, when it was given one', () => {
    const { campaign } = readCampaignRecord(
      bare({
        session: [
          { id: 'a', kind: 'scene', name: 'a', order: 2 },
          { id: 'b', kind: 'scene', name: 'b', order: 0 },
        ],
      }),
    );
    expect(campaign.session.map((i) => i.id)).toEqual(['b', 'a']);
  });

  it('leaves out a party row with no sheet, and one with half a sheet, and says both', () => {
    /*
     * The rule `gmStore.load()` already had - a row with no sheet has no
     * numbers and takes the screen down - and the clause added beside it. `p2`
     * used to survive this assertion: a name and nothing else was enough to be
     * stored and was never enough for `deriveStats`, and it is the shape that
     * took the GM screen down with `levelUpHistory.filter`. Two refusals, two
     * different sentences, and `p3` shows the campaign is not what is refused.
     */
    const { campaign, warnings } = readCampaignRecord(
      bare({
        party: [
          { id: 'p1' },
          { id: 'p2', sheet: { name: 'Kesh' } },
          { id: 'p3', sheet: newCharacter({ name: 'Ilya of the Ninth' }) },
        ],
      }),
    );
    expect(campaign.party.map((m) => m.id)).toEqual(['p3']);
    expect(warnings.join(' ')).toMatch(/no character sheet/);
    expect(warnings.join(' ')).toMatch(/"Kesh" is not a whole character|"Kesh"/);
  });

  it('does not accept a party tier the game has no tier for', () => {
    expect(readCampaignRecord(bare({ board: { partyTier: 9 } })).campaign.board.partyTier).toBe(1);
  });

  /*
   * Two things that arrived carrying one id, and the repair that keeps both.
   *
   * `readSessionItem` fills an id that is MISSING and can do no more than
   * that: it reads one row and cannot see the list the row is in. So a list
   * where two rows carry the same id gets through whole, and so does a fight
   * where two bodies do - and the two lists then fail in different shapes. A
   * row's id is read: `find` answers with the first and `map` answers with
   * both, one row read and two rows written. A body's id is never read at all
   * - `Scene.tsx` maps the fight and draws BOTH cards - so it is a write
   * address with two bodies behind it: one tap on one card's HP marks both,
   * and one REMOVE takes both off the table.
   *
   * These sit under the repairs that never cost the record because that is
   * precisely the argument. Dropping the later row, or the later body, would
   * restore the invariant in one line and cost the GM a row they typed or an
   * adversary standing at the table, with no warning able to bring either
   * back.
   */
  describe('two things that arrived sharing one id', () => {
    /** Deterministic, so a test can say which id was minted and which was kept. */
    const counter = (): (() => string) => {
      let n = 0;
      return () => `fresh-${String((n += 1))}`;
    };

    const sceneRow = (
      id: string,
      name: string,
      combatants: unknown[] = [],
    ): Record<string, unknown> => ({
      id,
      kind: 'scene',
      name,
      environmentRef: null,
      roster: [],
      adjustments: { easier: false, harder: false, damageBump: false },
      combatants,
    });

    const scopedClock = (id: string, sceneId: string): Record<string, unknown> => ({
      id,
      kind: 'countdown',
      name: id,
      primary: false,
      sceneId,
      countdown: { id, name: id, kind: 'standard', start: 4, value: 2, notes: '' },
    });

    /**
     * A countdown row exactly as `gmStore.addCountdown` mints one: the row's
     * id and the clock's are ONE string, on purpose, and the clock's is the
     * one `withCountdown` and `removeCountdown` key on.
     */
    const clockRow = (
      id: string,
      name: string,
      countdown: Record<string, unknown> = {},
    ): Record<string, unknown> => ({
      id,
      kind: 'countdown',
      name,
      primary: false,
      sceneId: null,
      countdown: { id, name, kind: 'standard', start: 4, value: 2, notes: '', ...countdown },
    });

    type ClockRow = Extract<SessionItem, { kind: 'countdown' }>;
    const clocksIn = (session: readonly SessionItem[]): ClockRow[] =>
      session.flatMap((i) => (i.kind === 'countdown' ? [i] : []));

    const body = (id: string, patch: Record<string, unknown> = {}): Record<string, unknown> => ({
      id,
      adversaryRef: 'acid-burrower',
      name: 'Acid Burrower',
      hp: { marked: 0, max: 8 },
      stress: { marked: 0, max: 3 },
      thresholds: [8, 15],
      difficulty: 14,
      spotlighted: false,
      notes: '',
      ...patch,
    });

    const fightIn = (item: SessionItem | undefined): SceneCombatant[] =>
      item?.kind === 'scene' || item?.kind === 'encounter' ? item.combatants : [];

    it('gives the later row a new id, keeps both rows, and says so', () => {
      const session = [sceneRow('s1', 'the first'), sceneRow('s1', 'the second')];
      const { campaign, warnings } = readCampaignRecord(bare({ session }), counter());
      expect(campaign.session.map((i) => i.name)).toEqual(['the first', 'the second']);
      const ids = campaign.session.map((i) => i.id);
      expect(new Set(ids).size).toBe(session.length);
      expect(ids[0]).toBe('s1');
      expect(warnings.filter((w) => /two rows/.test(w))).toHaveLength(1);
    });

    it('leaves a countdown scoped to that id on the row that kept it', () => {
      const session = [
        sceneRow('s1', 'the first'),
        sceneRow('s1', 'the second'),
        scopedClock('c1', 's1'),
      ];
      const { campaign, warnings } = readCampaignRecord(bare({ session }), counter());
      const clock = campaign.session.find((i) => i.id === 'c1');
      expect(clock?.kind === 'countdown' && clock.sceneId).toBe('s1');
      expect(campaign.session.find((i) => i.id === 's1')?.name).toBe('the first');
      // Nothing dangled: the id the clock names is still on a row.
      expect(warnings.join(' ')).not.toMatch(/no longer has/);
    });

    it('re-numbers every later one, and still says it once', () => {
      const session = [
        sceneRow('s1', 'the first'),
        sceneRow('s1', 'the second'),
        sceneRow('s1', 'the third'),
      ];
      const { campaign, warnings } = readCampaignRecord(bare({ session }), counter());
      expect(campaign.session).toHaveLength(session.length);
      const ids = campaign.session.map((i) => i.id);
      expect(new Set(ids).size).toBe(session.length);
      expect(ids.filter((id) => id === 's1')).toHaveLength(1);
      expect(warnings.filter((w) => /two rows/.test(w))).toHaveLength(1);
    });

    it('decides which row keeps the id by the order the list arrived in', () => {
      /*
       * Arrival, not `order`, and the difference is the whole reason this
       * repair runs before `deduped.sort`. Every pointer already written in
       * the record - a countdown's `sceneId`, the board's own - was written
       * against the list as it was STORED, and arrival is the only reading of
       * that list this pass still has. `order` is what the GM dragged the rows
       * into, and it is re-sorted further down; decide by it and the two rows
       * here swap, the later one keeps `s1`, and the scope lands on the other
       * row without a word.
       */
      const session = [
        { ...sceneRow('s1', 'first in the file'), order: 5 },
        { ...sceneRow('s1', 'second in the file'), order: 1 },
        { ...scopedClock('c1', 's1'), order: 3 },
      ];
      const { campaign } = readCampaignRecord(bare({ session }), counter());
      expect(campaign.session.find((i) => i.id === 's1')?.name).toBe('first in the file');
      const clock = campaign.session.find((i) => i.id === 'c1');
      expect(clock?.kind === 'countdown' && clock.sceneId).toBe('s1');
    });

    it('does not take the fresh id off a row further down that already had it', () => {
      /*
       * The promise the pass makes in its own voice - "the fresh id is checked
       * against every id in the list" - and the row-level twin of the
       * combatant test below it. Without the check the repaired row takes
       * `fresh-1` from the row that owned it, that row is re-numbered in turn,
       * and the clock scoped to `fresh-1` quietly lands on the row named
       * 'second': one collision turned into two, and no warning says which.
       */
      const session = [
        sceneRow('s1', 'first'),
        sceneRow('s1', 'second'),
        sceneRow('fresh-1', 'third'),
        scopedClock('c1', 'fresh-1'),
      ];
      const { campaign } = readCampaignRecord(bare({ session }), counter());
      expect(campaign.session.find((i) => i.id === 'fresh-1')?.name).toBe('third');
      expect(new Set(campaign.session.map((i) => i.id)).size).toBe(session.length);
      const clock = campaign.session.find((i) => i.id === 'c1');
      expect(clock?.kind === 'countdown' && clock.sceneId).toBe('fresh-1');
    });

    it('carries the fresh id onto the clock, which is the id the store writes through', () => {
      /*
       * A countdown row holds its id twice and `addCountdown` mints both as
       * one string. `withCountdown` (advance, reset) and `removeCountdown`
       * both key on the INNER one, so a repair that re-numbered the row alone
       * would hand back two clocks still answering to `c1`: one tap ticks
       * both, one DELETE takes both - the silent loss this repair exists to
       * refuse, moved one field down and announced in `warnings` as a fix.
       */
      const session = [clockRow('c1', 'the first'), clockRow('c1', 'the second')];
      const { campaign, warnings } = readCampaignRecord(bare({ session }), counter());
      const clocks = clocksIn(campaign.session);
      expect(clocks.map((i) => i.name)).toEqual(['the first', 'the second']);
      expect(new Set(clocks.map((i) => i.countdown.id)).size).toBe(session.length);
      expect(clocks[0]?.countdown.id).toBe('c1');
      // Both rows keep gmStore's invariant that the two ids are one string;
      // the repair is not allowed to be what breaks it.
      expect(clocks.map((i) => i.id === i.countdown.id)).toEqual([true, true]);
      expect(warnings.filter((w) => /two rows/.test(w))).toHaveLength(1);
    });

    it('leaves a clock that was already carrying an id of its own exactly where it is', () => {
      /*
       * The guard on the line above: the ids travel together only where they
       * were one string to begin with. A clock whose id somebody else minted
       * is a pointer of its own - screens hold it, `removeCountdown` answers
       * to it - and re-numbering the row it happens to sit on is no licence to
       * move it.
       */
      const session = [
        clockRow('c1', 'the first'),
        clockRow('c1', 'the second', { id: 'minted-elsewhere' }),
      ];
      const { campaign } = readCampaignRecord(bare({ session }), counter());
      const clocks = clocksIn(campaign.session);
      expect(clocks[1]?.countdown.id).toBe('minted-elsewhere');
      expect(clocks[1]?.id).not.toBe('c1');
    });

    it('re-numbers the second body in one fight and brings every mark with it', () => {
      const bodies = [
        body('acid-burrower-0', { name: 'the one in front', hp: { marked: 3, max: 8 } }),
        body('acid-burrower-0', {
          name: 'the one behind',
          hp: { marked: 5, max: 8 },
          stress: { marked: 2, max: 3 },
          thresholds: [9, 16],
          spotlighted: true,
          minionsRemaining: 4,
          notes: 'has the amulet',
        }),
      ];
      const { campaign, warnings } = readCampaignRecord(
        bare({ session: [sceneRow('s1', 's1', bodies)] }),
        counter(),
      );
      const fight = fightIn(campaign.session[0]);
      expect(fight).toHaveLength(bodies.length);
      expect(fight.map((c) => c.name)).toEqual(bodies.map((b) => b['name']));
      expect(new Set(fight.map((c) => c.id)).size).toBe(bodies.length);
      expect(fight[0]?.id).toBe('acid-burrower-0');
      // The body that moved, mark for mark: the id is the only thing that changed.
      expect(fight[1]).toEqual({ ...bodies[1], id: fight[1]?.id });
      expect(warnings.filter((w) => /two adversaries/.test(w))).toHaveLength(1);
    });

    it('picks a number nothing in that fight is already standing on', () => {
      const bodies = [
        body('acid-burrower-0', { name: 'one' }),
        body('acid-burrower-0', { name: 'two' }),
        body('acid-burrower-1', { name: 'three' }),
      ];
      const { campaign } = readCampaignRecord(
        bare({ session: [sceneRow('s1', 's1', bodies)] }),
        counter(),
      );
      const fight = fightIn(campaign.session[0]);
      expect(new Set(fight.map((c) => c.id)).size).toBe(bodies.length);
      // `-1` was already taken by a body further down, which keeps it: the
      // repair steps past every id in the list rather than only the ones
      // before it, so one collision cannot become two.
      expect(fight.find((c) => c.name === 'three')?.id).toBe('acid-burrower-1');
      expect(fight.find((c) => c.name === 'two')?.id).toBe('acid-burrower-2');
    });

    it('re-numbers every later body, not just the second, and still says it once', () => {
      /*
       * The body-side twin of "re-numbers every later one". With only two
       * colliding bodies the repair can forget each id it mints and still come
       * out right, because the second one is never consulted again. The third
       * is what makes remembering load-bearing: forget it and bodies two and
       * three both leave as `acid-burrower-1`, which is the state the repair
       * was written to end - restored by the repair itself, after the GM has
       * been told it was fixed.
       */
      const bodies = [
        body('acid-burrower-0', { name: 'one' }),
        body('acid-burrower-0', { name: 'two' }),
        body('acid-burrower-0', { name: 'three' }),
      ];
      const { campaign, warnings } = readCampaignRecord(
        bare({ session: [sceneRow('s1', 's1', bodies)] }),
        counter(),
      );
      const fight = fightIn(campaign.session[0]);
      expect(fight.map((c) => c.name)).toEqual(['one', 'two', 'three']);
      expect(fight.map((c) => c.id)).toEqual([
        'acid-burrower-0',
        'acid-burrower-1',
        'acid-burrower-2',
      ]);
      expect(new Set(fight.map((c) => c.id)).size).toBe(bodies.length);
      expect(warnings.filter((w) => /two adversaries/.test(w))).toHaveLength(1);
    });

    it('leaves the same id in two different rows alone, because that is what two fights look like', () => {
      /*
       * `makeCombatant` numbers from 0 in every fight it builds, so two rows
       * that each opened with the same adversary both hold an
       * `acid-burrower-0` and neither of them is wrong. This is the scope test
       * for the whole repair: widened by one row it would renumber a fight
       * nobody had touched, and every id the GM's own notes refer to would
       * move under them.
       */
      const session = [
        sceneRow('s1', 's1', [body('acid-burrower-0')]),
        sceneRow('s2', 's2', [body('acid-burrower-0')]),
      ];
      const { campaign, warnings } = readCampaignRecord(bare({ session }), counter());
      expect(campaign.session.flatMap((i) => fightIn(i).map((c) => c.id))).toEqual([
        'acid-burrower-0',
        'acid-burrower-0',
      ]);
      expect(warnings).toEqual([]);
    });

    it('defends the legacy encounter row and the board’s own fight from the same line', () => {
      /*
       * One function reads all three lists, so the repair is written once. The
       * `encounter` arm is the one nothing can mint any more and every saved
       * campaign may still be carrying; its bodies are only counted on the
       * glass today rather than addressed, which is precisely why the repair
       * must not be per-arm - the day anything puts one of them back in play
       * it arrives holding whatever id this function gave it, under the same
       * id-keyed `map` and `filter` as the row this build mints. An `if` per
       * arm is how two policies for one invariant start.
       */
      const bodies = [
        body('acid-burrower-0', { name: 'one' }),
        body('acid-burrower-0', { name: 'two' }),
      ];
      const { campaign, warnings } = readCampaignRecord(
        bare({
          session: [
            {
              id: 'legacy',
              kind: 'encounter',
              name: 'legacy',
              roster: [],
              adjustments: { easier: false, harder: false, damageBump: false },
              combatants: bodies,
            },
          ],
          board: { combatants: bodies },
        }),
        counter(),
      );
      expect(new Set(fightIn(campaign.session[0]).map((c) => c.id)).size).toBe(bodies.length);
      expect(new Set(campaign.board.combatants.map((c) => c.id)).size).toBe(bodies.length);
      expect(warnings.filter((w) => /two adversaries/.test(w))).toHaveLength(1);
    });
  });
});

describe('walking a campaign record forward', () => {
  it('passes a current record through untouched, and stamps it', () => {
    const { record, from, applied } = migrateCampaignRecord({
      schemaVersion: CAMPAIGN_SCHEMA_VERSION,
      x: 1,
    });
    expect(record).toEqual({ schemaVersion: CAMPAIGN_SCHEMA_VERSION, x: 1 });
    expect(from).toBe(CAMPAIGN_SCHEMA_VERSION);
    expect(applied).toEqual([]);
  });

  it('refuses a version below the oldest any build has written', () => {
    expect(() => migrateCampaignRecord({ schemaVersion: OLDEST_READABLE_CAMPAIGN - 1 })).toThrow(
      /no released version of this app has ever written/,
    );
  });

  it('carries the version on the error, so a caller can say which record', () => {
    try {
      migrateCampaignRecord({ schemaVersion: CAMPAIGN_SCHEMA_VERSION + 4 });
      expect.unreachable('should have thrown');
    } catch (error) {
      expect(error).toBeInstanceOf(SchemaError);
      expect((error as SchemaError).version).toBe(CAMPAIGN_SCHEMA_VERSION + 4);
    }
  });
});

describe('what campaign schema 3 added, held down', () => {
  /*
   * The gate's own lesson, applied while the paint is wet: a green suite is not
   * a verification. Each of these fails if the field it names stops surviving a
   * read, which is the only property the bump actually bought.
   */
  const v3 = (): Record<string, unknown> => readFixture(3);

  it('carries the fight on the scene row, which is the whole of decision 1', () => {
    const { campaign } = readCampaignRecord(v3());
    const scene = campaign.session.find((i) => i.kind === 'scene');
    expect(scene?.kind === 'scene' && scene.roster).toEqual([
      { ref: 'jagged-knife-bandit', count: 2 },
    ]);
    expect(scene?.kind === 'scene' && scene.adjustments.harder).toBe(true);
    // The fight as it is being fought is never in the plan, only the plan for it.
    expect(scene?.kind === 'scene' && scene.combatants).toEqual([]);
  });

  it('still reads the legacy encounter row, because saved campaigns carry one', () => {
    /*
     * The half of decision 1 that is easy to lose. `encounter` left
     * `SESSION_ITEM_KINDS` so nothing can mint one; the union arm stayed so
     * every campaign already on a disk still opens. A build that dropped the
     * arm would read this row as `unreadable` and then write that back.
     */
    const { campaign, warnings } = readCampaignRecord(v3());
    const enc = campaign.session.find((i) => i.kind === 'encounter');
    expect(enc?.kind).toBe('encounter');
    expect(enc?.kind === 'encounter' && enc.roster.length).toBeGreaterThan(0);
    // Nothing in the session list needed saying. The fixture's party stub is
    // refused whatever this row does, and the walk above is where that is held.
    expect(warnings.filter((w) => !w.includes('not a whole character'))).toEqual([]);
  });

  it('keeps the triad, the owner and every beat on a countdown', () => {
    const { campaign } = readCampaignRecord(v3());
    const row = campaign.session.find((i) => i.kind === 'countdown');
    const clock = row?.kind === 'countdown' ? row.countdown : null;
    expect(clock?.activation).toBe('the party first sets foot on the ice');
    expect(clock?.advancement).toBe('one tick per failed crossing roll');
    expect(clock?.effect).toBe('the ice gives way and everyone standing on it falls in');
    expect(clock?.owner).toBe('9a1f2b3c-4d5e-4f60-8712-a3b4c5d6e7f8');
    expect(clock?.beats).toEqual([
      'a crack runs out from the bank',
      'water wells up over the boots',
    ]);
  });

  it('leaves the beats alone when there are fewer of them than there are ticks', () => {
    // A GM who has written the first two beats of a six-tick clock is the
    // normal case. Padding would make "unwritten" and "deliberately blank"
    // indistinguishable; truncating would eat words on a clock that shortened.
    const { campaign } = readCampaignRecord(v3());
    const row = campaign.session.find((i) => i.kind === 'countdown');
    const clock = row?.kind === 'countdown' ? row.countdown : null;
    expect(clock?.beats.length).toBe(2);
    expect(clock?.start).toBe(6);
  });

  it('opens the archive and the register, and orders the archive by when it closed', () => {
    const { campaign } = readCampaignRecord(v3());
    expect(campaign.archive).toHaveLength(1);
    expect(campaign.archive[0]!.name).toBe('The first night out');
    expect(campaign.archive[0]!.items.map((i) => i.kind)).toEqual(['scene']);
    expect(campaign.register.map((e) => e.name)).toContain('Old Hessa, the ferrywoman');
  });

  it('wraps a register entry whose kind this build has never heard of', () => {
    /*
     * The same promise `SessionItem` and `LinkTarget` make, made again one
     * level down. A GM who wrote forty people and finds thirty-nine has no way
     * to learn which one left, so an entry this build cannot read comes back
     * out of the file it went into.
     */
    const { campaign } = readCampaignRecord(v3());
    const odd = campaign.register.find((e) => e.kind === 'unreadable');
    expect(odd).toBeDefined();
    expect(odd?.name).toBe('The drowned king returns');
    expect(odd?.kind === 'unreadable' && odd.why).toContain('prophecy');
    expect(odd?.kind === 'unreadable' && odd.raw).toContain('prophecy');
  });

  it('a campaign written now and read back keeps both new arrays', () => {
    // `newCampaign` seeds them, the reader names them. A `Campaign` literal
    // that forgot either would drop it on the first save/load round trip.
    const { campaign } = readCampaignRecord(bare({ archive: [], register: [] }));
    expect(campaign.archive).toEqual([]);
    expect(campaign.register).toEqual([]);
  });
});

describe('the bumps, and the record they must not touch', () => {
  /*
   * The whole justification for schema 2, restated as an assertion.
   *
   * The version moved so that an *older* build refuses a record carrying a
   * `url` or a `note` row. Without the bump, `readSessionItem` in the old build
   * wraps both as `unreadable` - on purpose, so the row is kept and named - and
   * `gmStore`'s 400ms debounce then writes that reading back, so the GM's row
   * is destroyed on the older device and nothing anywhere says why.
   *
   * Nothing in a v1 record is wrong, so the converter changes no field.
   *
   * Schema 3 is the same argument with more at stake. It moved so that an older
   * build refuses a record whose `scene` rows carry a fight, whose countdowns
   * carry the Activation / Advancement / Effect triad, and which has an
   * `archive` and a `register` at all - every one of which a schema-2 reader
   * would drop on the floor and then write back over. Nothing in a v2 record is
   * wrong either, so that converter changes no field either.
   *
   * Schema 4 is the same argument on two pointers. It moved so that an older
   * build refuses a record whose board names the scene row its fight came from
   * and whose countdown rows name the scene they belong to. A schema-3 reader
   * does not fail on either - it rebuilds `board` and every row field by field
   * and drops what it does not name - so it would park a fight that belongs to
   * no row, hand every scene clock back to the campaign, and let the 400 ms
   * debounce write that reading back. Nothing in a v3 record is wrong, so that
   * converter changes no field either.
   */
  it('carries one converter per bump, in order, and none of them is a repair', () => {
    // Derived from the constant rather than frozen as a literal: a third bump
    // adds one entry here and does not have to remember to edit two lines.
    expect(CAMPAIGN_MIGRATIONS.map((m) => m.from)).toEqual([1, 2, 3]);
    expect(CAMPAIGN_SCHEMA_VERSION).toBe(4);
    expect(CAMPAIGN_MIGRATIONS).toHaveLength(CAMPAIGN_SCHEMA_VERSION - OLDEST_READABLE_CAMPAIGN);
  });

  it('gives a v1 record back byte for byte, apart from the stamp, across all three bumps', () => {
    // Deep equality against the fixture itself rather than against a list of
    // fields somebody remembered to check: an `apply` that dropped `party`,
    // renamed `board.partyTier`, or normalised a countdown on the way through
    // fails here without anyone having to have predicted which field it was.
    const fixture = readFixture(1);
    const { record, from, applied } = migrateCampaignRecord(fixture);

    expect(from).toBe(1);
    // Every converter ran, in order, and each said what it was for.
    expect(applied).toEqual(CAMPAIGN_MIGRATIONS.map((m) => m.note));
    expect(record).toEqual({ ...fixture, schemaVersion: CAMPAIGN_SCHEMA_VERSION });
    // Deep equality is not enough on its own to earn the words "byte for byte":
    // `toEqual` ignores key order and treats an absent key and an
    // `undefined`-valued one as the same. The `.dhcampaign` checksum is
    // computed over `JSON.stringify`, so a converter that reordered keys or
    // turned a value into `undefined` would pass the line above and still make
    // the file this app writes fail to verify against the file it reads.
    expect(JSON.stringify(record)).toBe(
      JSON.stringify({ ...fixture, schemaVersion: CAMPAIGN_SCHEMA_VERSION }),
    );
    // Said separately, because the two assertions above would also pass if both
    // sides were 1 and the bump had never happened.
    expect(record['schemaVersion']).toBe(4);
  });

  it('hands the chain a copy rather than the record it was given', () => {
    /*
     * Asserted against `applyChain` and not against `migrateCampaignRecord`,
     * because the wrapper spreads a `schemaVersion` onto whatever comes back
     * and that spread allocates an object either way - so a test one level up
     * passes whether the converter copies or returns its argument, which is a
     * test that cannot fail.
     *
     * This one can: `apply: (r) => r` turns the first assertion red. It matters
     * because the chain is the one part of the schema policy that is pure, and
     * a converter handing back its input makes every later step free to mutate
     * a caller's record in place.
     */
    const input: Record<string, unknown> = { schemaVersion: 1, id: 'c-1' };
    const { record, applied } = applyChain(input, 1, 2, CAMPAIGN_MIGRATIONS);
    expect(record).not.toBe(input);
    expect(record).toEqual(input);
    expect(applied).toHaveLength(1);
  });

  it('reads a v1 record into a campaign with nothing missing and nothing invented', () => {
    const { campaign, warnings } = readCampaignRecord(readFixture(1));
    // Same exception as the walk: the frozen fixture's party row is a stub, and
    // this test is about the session list rather than the board.
    expect(warnings.filter((w) => !w.includes('not a whole character'))).toEqual([]);
    // A v1 record has neither of the two new kinds in it, and this build must
    // not conjure one - an empty `url` row appearing here would mean the reader
    // was inventing rows rather than reading them.
    expect(campaign.session.map((i) => i.kind)).not.toContain('url');
    expect(campaign.session.map((i) => i.kind)).not.toContain('note');
    expect(campaign.session).toHaveLength(5);
  });
});

describe('the v2 fixture, which is the first one with the new rows in it', () => {
  const v2 = (): Campaign => readCampaignRecord(readFixture(2)).campaign;

  it('is seven rows, the five from v1 and the two the bump is for', () => {
    expect(v2().session.map((i) => i.kind)).toEqual([
      'scene',
      'encounter',
      'countdown',
      'link',
      'link',
      'url',
      'note',
    ]);
  });

  it('keeps the web address exactly as the parser normalises it', () => {
    const row = v2().session.find((i) => i.kind === 'url');
    expect(row?.kind === 'url' && row.href).toBe(
      'https://maps.example.org/sablewood/ford?layer=winter',
    );
    expect(row?.name).toBe("The table's map board");
  });

  it('keeps the note’s centred heading, its emphasis and its bullets', () => {
    // Every one of the four things the format exists to carry, in one fixture,
    // because a fixture that only proves paragraphs survive proves the easy
    // half of a format whose hard half is centring.
    const row = v2().session.find((i) => i.kind === 'note');
    expect(row?.kind === 'note').toBe(true);
    if (row?.kind !== 'note') return;

    const heading = row.note[0]!;
    expect(heading.type).toBe('heading');
    expect(heading.type !== 'bullets' && heading.align).toBe('center');
    expect(heading.type !== 'bullets' && heading.spans[0]!.bold).toBe(true);

    const paragraph = row.note[1]!;
    expect(paragraph.type !== 'bullets' && paragraph.spans.map((s) => s.text).join('')).toBe(
      'Rhys wants the cargo, not the fight. She will say so only if someone asks her name.',
    );
    expect(paragraph.type !== 'bullets' && paragraph.spans.some((s) => s.italic)).toBe(true);

    const bullets = row.note[2]!;
    expect(bullets.type).toBe('bullets');
    expect(bullets.type === 'bullets' && bullets.items).toHaveLength(3);
  });
});

// ---------------------------------------------------------------------------

/**
 * The two total writers of a countdown's scope.
 *
 * The invariant - a clock a scene owns is never the pinned one - has three
 * enforcers and every one of them is needed: `withPrimaryCountdown` refuses to
 * pin a scoped clock, `withSceneScope` clears a pin when a scene takes a clock,
 * and `readCampaignRecord` repairs a record that arrived in the forbidden state
 * anyway. A clause in only one of them leaves the other route open.
 */
describe('giving a countdown to a scene, and taking it back', () => {
  const sceneRow = (id: string): Record<string, unknown> => ({
    id,
    kind: 'scene',
    name: id,
    environmentRef: null,
    roster: [],
    adjustments: { easier: false, harder: false, damageBump: false },
    combatants: [],
  });
  const clock = (id: string, primary = false, kind = 'standard'): Record<string, unknown> => ({
    id,
    kind: 'countdown',
    name: id,
    primary,
    countdown: { id, name: id, kind, start: 6, value: 4, notes: '' },
  });

  const read = (session: Record<string, unknown>[]) =>
    readCampaignRecord(bare({ session })).campaign.session;

  it('hands a clock to a scene, and back to the campaign', () => {
    const session = read([sceneRow('s1'), clock('a')]);
    const given = withSceneScope(session, 'a', 's1');
    expect(given.find((i) => i.id === 'a')?.kind === 'countdown' && given.find((i) => i.id === 'a')).toBeTruthy();
    const scoped = given.find((i) => i.id === 'a');
    expect(scoped?.kind === 'countdown' && scoped.sceneId).toBe('s1');

    const back = withSceneScope(given, 'a', null);
    const unscoped = back.find((i) => i.id === 'a');
    expect(unscoped?.kind === 'countdown' && unscoped.sceneId).toBe(null);
  });

  it('clears the pin when a scene takes a clock that was on the top bar', () => {
    // The other half of the invariant. `withPrimaryCountdown` refuses to SET
    // the flag on a scoped clock; this clears one a clock already had, and
    // without it the forbidden state would sit on the glass until a reload.
    const session = read([sceneRow('s1'), clock('a', true)]);
    expect(primaryCountdownOf(session)?.id).toBe('a');

    const scoped = withSceneScope(session, 'a', 's1');
    expect(primaryCountdownOf(scoped)).toBe(null);
    const row = scoped.find((i) => i.id === 'a');
    expect(row?.kind === 'countdown' && row.primary).toBe(false);
  });

  it('does not re-pin a clock when the campaign takes it back', () => {
    // A countdown does not become the one on the top bar as a side effect of
    // losing a scope.
    const session = read([sceneRow('s1'), clock('a', true)]);
    const scoped = withSceneScope(session, 'a', 's1');
    const back = withSceneScope(scoped, 'a', null);
    expect(primaryCountdownOf(back)).toBe(null);
  });

  it('leaves a clock that was never pinned exactly as pinned as it was', () => {
    const session = read([sceneRow('s1'), clock('a'), clock('b', true)]);
    const scoped = withSceneScope(session, 'a', 's1');
    expect(primaryCountdownOf(scoped)?.id).toBe('b');
  });

  it('touches nothing but the row it names', () => {
    const session = read([sceneRow('s1'), clock('a'), clock('b')]);
    const scoped = withSceneScope(session, 'a', 's1');
    const other = scoped.find((i) => i.id === 'b');
    expect(other?.kind === 'countdown' && other.sceneId).toBe(null);
  });
});

describe('the countdowns one scope owns', () => {
  const sceneRow = (id: string): Record<string, unknown> => ({
    id,
    kind: 'scene',
    name: id,
    environmentRef: null,
    roster: [],
    adjustments: { easier: false, harder: false, damageBump: false },
    combatants: [],
  });
  const clock = (id: string, sceneId: string | null = null): Record<string, unknown> => ({
    id,
    kind: 'countdown',
    name: id,
    primary: false,
    sceneId,
    countdown: { id, name: id, kind: 'standard', start: 6, value: 4, notes: '' },
  });

  it('answers one scope at a time, and null is the campaign’s own', () => {
    const { campaign } = readCampaignRecord(
      bare({ session: [sceneRow('s1'), clock('a'), clock('b', 's1'), clock('c', 's1')] }),
    );
    expect(countdownsIn(campaign.session, null).map((c) => c.id)).toEqual(['a']);
    expect(countdownsIn(campaign.session, 's1').map((c) => c.id)).toEqual(['b', 'c']);
  });

  it('leaves `countdownsOf` meaning every clock in the campaign', () => {
    /*
     * Three callers depend on that: the store's derived `countdowns`, the
     * export, and the long rest. Scope is an argument at a call site and never
     * a narrowing of what "the campaign's countdowns" means - a narrowed
     * `countdownsOf` would take the forest's long-term clock off the list a
     * rest may advance, with no error message anywhere.
     */
    const { campaign } = readCampaignRecord(
      bare({ session: [sceneRow('s1'), clock('a'), clock('b', 's1')] }),
    );
    expect(countdownsOf(campaign.session).map((c) => c.id)).toEqual(['a', 'b']);
  });

  it('gives an empty list for a scene that owns nothing', () => {
    const { campaign } = readCampaignRecord(bare({ session: [sceneRow('s1'), clock('a')] }));
    expect(countdownsIn(campaign.session, 's1')).toEqual([]);
  });
});
