/**
 * The campaign schema, held to the same policy as the character one.
 *
 * Architecture 6.1 is one rule - "no schema ships without its converter" - and
 * campaigns are the first record in this app to be governed by it that is not
 * a `Character`. The temptation was to write a second, softer policy for a
 * store nobody has data in yet. That is exactly backwards: today is the only
 * day the enforcement is free, because on the day of the first bump every
 * campaign in the world is already on somebody's phone.
 *
 * So this file asks of `CAMPAIGN_SCHEMA_VERSION` precisely what
 * `tests/store/migrations.test.ts` asks of `SCHEMA_VERSION`:
 *
 *   - no gap in the chain between the oldest readable version and this one;
 *   - a committed fixture per readable version, written by the build that
 *     shipped it and never regenerated by a later one;
 *   - every fixture still reads into a campaign at the current schema, with
 *     the fields a GM would notice still in it.
 *
 * Plus the two things the character policy does not have to worry about,
 * because a character has no list of heterogeneous rows in it: an item this
 * build cannot read is kept rather than dropped, and a link that points at
 * something unrecognised is still a link.
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import {
  CAMPAIGN_MIGRATIONS,
  CAMPAIGN_SCHEMA_VERSION,
  CampaignReadError,
  countdownsOf,
  emptyBoard,
  migrateCampaignRecord,
  newCampaign,
  OLDEST_READABLE_CAMPAIGN,
  primaryCountdownOf,
  readCampaignRecord,
  withPrimaryCountdown,
  type Campaign,
  type SessionItem,
} from '../../shared/campaigns.ts';
import { missingConverters, readableVersions, SchemaError } from '../../shared/migrations.ts';
import { MAX_FEAR, SCHEMA_VERSION } from '../../shared/types.ts';

const FIXTURES = fileURLToPath(new URL('../fixtures/schema', import.meta.url));

const readFixture = (version: number): Record<string, unknown> =>
  JSON.parse(readFileSync(join(FIXTURES, `v${version}.campaign.json`), 'utf8')) as Record<
    string,
    unknown
  >;

const versions = (): number[] =>
  readableVersions(OLDEST_READABLE_CAMPAIGN, CAMPAIGN_SCHEMA_VERSION);

/** A minimal record: only what `readCampaignRecord` genuinely insists on. */
const bare = (patch: Record<string, unknown> = {}): Record<string, unknown> => ({
  id: 'campaign-1',
  schemaVersion: CAMPAIGN_SCHEMA_VERSION,
  name: 'A Campaign',
  ...patch,
});

describe('the policy, applied to a second schema', () => {
  it('numbers campaigns separately from characters, on purpose', () => {
    // Not an accident of ordering: folding campaigns into SCHEMA_VERSION would
    // make every future campaign change a character migration, and force every
    // committed character fixture to be rewritten for a field no character has.
    expect(CAMPAIGN_SCHEMA_VERSION).not.toBe(SCHEMA_VERSION);
  });

  it('has a converter for every step from the oldest readable version to this one', () => {
    const gaps = missingConverters(
      OLDEST_READABLE_CAMPAIGN,
      CAMPAIGN_SCHEMA_VERSION,
      CAMPAIGN_MIGRATIONS,
    );
    expect(
      gaps,
      `campaign schema ${gaps.join(', ')} can be read by no converter in shared/campaigns.ts.`,
    ).toEqual([]);
  });

  it('would fail on a bump that shipped without its converter', () => {
    // The teeth, without touching the constant. If this ever comes back empty
    // the check above has gone vacuous - passing because the range is empty
    // rather than because it is covered.
    expect(
      missingConverters(
        CAMPAIGN_SCHEMA_VERSION,
        CAMPAIGN_SCHEMA_VERSION + 1,
        CAMPAIGN_MIGRATIONS,
      ),
    ).toEqual([CAMPAIGN_SCHEMA_VERSION]);
  });

  it('carries no converter for a version this build has not left yet', () => {
    const ahead = CAMPAIGN_MIGRATIONS.filter((m) => m.from >= CAMPAIGN_SCHEMA_VERSION);
    expect(ahead.map((m) => m.from)).toEqual([]);
  });

  it('gives every converter a line of changelog', () => {
    for (const m of CAMPAIGN_MIGRATIONS) {
      expect(m.note.trim().length, `campaign schema ${m.from}`).toBeGreaterThan(0);
    }
  });
});

describe('the committed fixtures', () => {
  it('has one per readable version', () => {
    for (const version of versions()) {
      expect(() => readFixture(version), `no committed fixture for campaign v${version}`).not.toThrow();
    }
  });

  it('keeps each fixture at the version its name claims', () => {
    // A fixture rewritten by a later build proves only that the current code
    // can read its own output, which is not the question being asked.
    for (const version of versions()) {
      expect(readFixture(version)['schemaVersion'], `v${version}.campaign.json`).toBe(version);
    }
  });

  for (const version of versions()) {
    it(`still opens the campaign schema ${version} record whole`, () => {
      const { campaign, warnings } = readCampaignRecord(readFixture(version));

      expect(warnings).toEqual([]);
      expect(campaign.schemaVersion).toBe(CAMPAIGN_SCHEMA_VERSION);

      // Not just "it parsed". These are the things a GM would notice missing.
      expect(campaign.name).toBe('The Sablewood Winter');
      expect(campaign.fear).toBe(7);
      expect(campaign.session).toHaveLength(5);
      expect(campaign.session.map((i) => i.kind)).toEqual([
        'scene',
        'encounter',
        'countdown',
        'link',
        'link',
      ]);
      expect(campaign.board.environmentRef).toBe('raging-river');
      expect(campaign.party).toHaveLength(1);
      expect(campaign.party[0]!.sheet.name).toBe('Ilya of the Ninth');
      expect(campaign.party[0]!.tracks.stress).toBe(4);

      const fight = campaign.session.find((i) => i.kind === 'encounter');
      expect(fight?.kind === 'encounter' && fight.roster).toHaveLength(2);
      expect(fight?.kind === 'encounter' && fight.combatants[0]?.hp.marked).toBe(3);

      expect(primaryCountdownOf(campaign.session)?.value).toBe(4);
    });
  }
});

describe('a campaign owns its own things, and not the player characters', () => {
  it('holds a name, a session list, Fear, countdowns and a party', () => {
    const c = newCampaign('Ashes of Rivermarch', '2026-08-16T10:00:00.000Z', 'campaign-1');
    expect(c.name).toBe('Ashes of Rivermarch');
    expect(c.session).toEqual([]);
    expect(c.fear).toBe(0);
    expect(c.party).toEqual([]);
    expect(c.board).toEqual(emptyBoard());
  });

  it('stamps itself with the campaign schema, never the character one', () => {
    const c = newCampaign('x', '2026-08-16T10:00:00.000Z', 'campaign-1');
    expect(c.schemaVersion).toBe(CAMPAIGN_SCHEMA_VERSION);
  });
});

describe('the two refusals, and nothing else', () => {
  it('will not read a record a newer build wrote, and says to update the app', () => {
    expect(() =>
      readCampaignRecord(bare({ schemaVersion: CAMPAIGN_SCHEMA_VERSION + 1 })),
    ).toThrow(SchemaError);
    expect(() =>
      readCampaignRecord(bare({ schemaVersion: CAMPAIGN_SCHEMA_VERSION + 1 })),
    ).toThrow(/newer version of the app.*Update the app/s);
  });

  it('will not read a record with no id, because there is nothing to write back to', () => {
    // Inventing one here is how a campaign gets duplicated on every launch.
    const { id, ...rest } = bare();
    expect(id).toBeDefined();
    expect(() => readCampaignRecord(rest)).toThrow(CampaignReadError);
    expect(() => readCampaignRecord(rest)).toThrow(/nothing to write it back to/);
  });

  it('opens a record that is otherwise almost empty', () => {
    const { campaign } = readCampaignRecord(bare());
    expect(campaign.name).toBe('A Campaign');
    expect(campaign.session).toEqual([]);
    expect(campaign.board.region).toBe('encounter');
    expect(campaign.board.partyTier).toBe(1);
  });

  it('reads a record with no stamp as this build’s, the way a hand-edited file arrives', () => {
    const { schemaVersion, ...rest } = bare();
    expect(schemaVersion).toBe(CAMPAIGN_SCHEMA_VERSION);
    expect(readCampaignRecord(rest).campaign.schemaVersion).toBe(CAMPAIGN_SCHEMA_VERSION);
  });

  /*
   * `board.region` is a union in the type and a list in the reader, and only
   * the list is load-bearing on the way in from a disk. Widening one and
   * forgetting the other typechecks perfectly and loses the new tool on every
   * single reload - silently, because the fallback is a real region.
   */
  it('keeps a region this build knows, including the one added last', () => {
    const { campaign } = readCampaignRecord(bare({ board: { region: 'reference' } }));
    expect(campaign.board.region).toBe('reference');
  });

  it('falls back for a region no build knows, which is what makes widening safe', () => {
    // The guarantee the reference tab was added on: an older build meeting a
    // newer record forgets which tool was open and loses nothing else.
    const { campaign } = readCampaignRecord(bare({ board: { region: 'holodeck' } }));
    expect(campaign.board.region).toBe('encounter');
  });
});

describe('a session item this build cannot read', () => {
  const withItem = (item: unknown): Campaign =>
    readCampaignRecord(bare({ session: [item] })).campaign;

  it('is kept and named, not dropped', () => {
    // The failure this repo has shipped twice: the list comes back one row
    // shorter and the GM has no way to learn which row it was.
    const kept = withItem({ id: 'i1', kind: 'handout', name: 'The letter' });
    expect(kept.session).toHaveLength(1);
    expect(kept.session[0]!.kind).toBe('unreadable');
    expect(kept.session[0]!.name).toBe('The letter');
  });

  it('says what it was, in a sentence a screen can print', () => {
    const item = withItem({ id: 'i1', kind: 'handout', name: 'The letter' }).session[0]!;
    expect(item.kind === 'unreadable' && item.why).toMatch(/no "handout" item/);
  });

  it('keeps the bytes it arrived as, so nothing is actually lost', () => {
    const item = withItem({ id: 'i1', kind: 'handout', url: 'x', name: '' }).session[0]!;
    expect(item.kind === 'unreadable' && JSON.parse(item.raw)).toMatchObject({
      kind: 'handout',
      url: 'x',
    });
  });

  it('does not wrap an already-wrapped item a second time', () => {
    const once = withItem({ id: 'i1', kind: 'handout', name: 'x' }).session[0]!;
    const twice = withItem(once).session[0]!;
    expect(twice.kind === 'unreadable' && JSON.parse(twice.raw)).toMatchObject({ kind: 'handout' });
  });

  it('warns about it, rather than only recording it', () => {
    const { warnings } = readCampaignRecord(bare({ session: [{ id: 'i1', kind: 'handout' }] }));
    expect(warnings.join(' ')).toMatch(/could not be read/);
  });
});

describe('a link, which never leaves the app', () => {
  const target = (t: unknown): SessionItem =>
    readCampaignRecord(bare({ session: [{ id: 'i1', kind: 'link', name: 'n', target: t }] }))
      .campaign.session[0]!;

  it('reads the four things a link may point at', () => {
    for (const kind of ['adversary', 'environment', 'domainCard', 'rule']) {
      const item = target({ kind, ref: 'r' });
      expect(item.kind === 'link' && item.target.kind).toBe(kind);
    }
  });

  it('keeps a target it does not recognise, and remembers what it called itself', () => {
    const item = target({ kind: 'campaignFrame', ref: 'the-witherwild' });
    expect(item.kind).toBe('link');
    expect(item.kind === 'link' && item.target.kind).toBe('unknown');
    expect(item.kind === 'link' && item.target.kind === 'unknown' && item.target.named).toBe(
      'campaignFrame',
    );
    expect(item.kind === 'link' && item.target.ref).toBe('the-witherwild');
  });

  it('keeps the ref even when there is no kind at all', () => {
    const item = target({ ref: 'the-witherwild' });
    expect(item.kind === 'link' && item.target.ref).toBe('the-witherwild');
  });
});

describe('countdowns, which live in the session list', () => {
  const countdownItem = (id: string, primary: boolean): Record<string, unknown> => ({
    id,
    kind: 'countdown',
    name: id,
    primary,
    countdown: { id, name: id, kind: 'standard', start: 4, value: 2, notes: '' },
  });

  it('collects them in list order', () => {
    const { campaign } = readCampaignRecord(
      bare({ session: [countdownItem('a', false), countdownItem('b', true)] }),
    );
    expect(countdownsOf(campaign.session).map((c) => c.id)).toEqual(['a', 'b']);
  });

  it('lets at most one be the primary one', () => {
    // Two rows both claiming to be the one the GM is watching is not a state
    // any screen can draw honestly, and a hand-edited file can reach it.
    const { campaign, warnings } = readCampaignRecord(
      bare({ session: [countdownItem('a', true), countdownItem('b', true)] }),
    );
    expect(campaign.session.filter((i) => i.kind === 'countdown' && i.primary)).toHaveLength(1);
    expect(primaryCountdownOf(campaign.session)?.id).toBe('a');
    expect(warnings.join(' ')).toMatch(/more than one countdown/);
  });

  it('moves the flag rather than adding a second one', () => {
    const { campaign } = readCampaignRecord(
      bare({ session: [countdownItem('a', true), countdownItem('b', false)] }),
    );
    const moved = withPrimaryCountdown(campaign.session, 'b');
    expect(moved.filter((i) => i.kind === 'countdown' && i.primary).map((i) => i.id)).toEqual(['b']);
  });

  it('clears the flag when told to make a non-countdown primary', () => {
    const { campaign } = readCampaignRecord(bare({ session: [countdownItem('a', true)] }));
    expect(withPrimaryCountdown(campaign.session, null).some((i) => i.kind === 'countdown' && i.primary)).toBe(
      false,
    );
  });

  it('brings a countdown value back inside its own start', () => {
    const { campaign } = readCampaignRecord(
      bare({
        session: [
          {
            id: 'a',
            kind: 'countdown',
            name: 'a',
            primary: false,
            countdown: { id: 'a', name: 'a', kind: 'standard', start: 4, value: 99, notes: '' },
          },
        ],
      }),
    );
    expect(countdownsOf(campaign.session)[0]!.value).toBe(4);
  });
});

describe('the repairs, which never cost the record', () => {
  it('brings a Fear pool from outside the ladder back onto it, and says so', () => {
    const { campaign, warnings } = readCampaignRecord(bare({ fear: 99 }));
    expect(campaign.fear).toBe(MAX_FEAR);
    expect(warnings.join(' ')).toMatch(/Fear pool held 99/);
  });

  it('re-numbers the order so a list written without one keeps its order', () => {
    const { campaign } = readCampaignRecord(
      bare({
        session: [
          { id: 'a', kind: 'scene', name: 'a' },
          { id: 'b', kind: 'scene', name: 'b' },
          { id: 'c', kind: 'scene', name: 'c' },
        ],
      }),
    );
    expect(campaign.session.map((i) => i.id)).toEqual(['a', 'b', 'c']);
    expect(campaign.session.map((i) => i.order)).toEqual([0, 1, 2]);
  });

  it('sorts by the order it was given, when it was given one', () => {
    const { campaign } = readCampaignRecord(
      bare({
        session: [
          { id: 'a', kind: 'scene', name: 'a', order: 2 },
          { id: 'b', kind: 'scene', name: 'b', order: 0 },
        ],
      }),
    );
    expect(campaign.session.map((i) => i.id)).toEqual(['b', 'a']);
  });

  it('leaves out a party row with no sheet, and says that too', () => {
    // The one thing here that is dropped, and the rule `gmStore.load()` already
    // had: a row with no sheet has no numbers and takes the screen down.
    const { campaign, warnings } = readCampaignRecord(
      bare({ party: [{ id: 'p1' }, { id: 'p2', sheet: { name: 'Kesh' } }] }),
    );
    expect(campaign.party.map((m) => m.id)).toEqual(['p2']);
    expect(warnings.join(' ')).toMatch(/no character sheet/);
  });

  it('does not accept a party tier the game has no tier for', () => {
    expect(readCampaignRecord(bare({ board: { partyTier: 9 } })).campaign.board.partyTier).toBe(1);
  });
});

describe('walking a campaign record forward', () => {
  it('passes a current record through untouched, and stamps it', () => {
    const { record, from, applied } = migrateCampaignRecord({
      schemaVersion: CAMPAIGN_SCHEMA_VERSION,
      x: 1,
    });
    expect(record).toEqual({ schemaVersion: CAMPAIGN_SCHEMA_VERSION, x: 1 });
    expect(from).toBe(CAMPAIGN_SCHEMA_VERSION);
    expect(applied).toEqual([]);
  });

  it('refuses a version below the oldest any build has written', () => {
    expect(() => migrateCampaignRecord({ schemaVersion: OLDEST_READABLE_CAMPAIGN - 1 })).toThrow(
      /no released version of this app has ever written/,
    );
  });

  it('carries the version on the error, so a caller can say which record', () => {
    try {
      migrateCampaignRecord({ schemaVersion: CAMPAIGN_SCHEMA_VERSION + 4 });
      expect.unreachable('should have thrown');
    } catch (error) {
      expect(error).toBeInstanceOf(SchemaError);
      expect((error as SchemaError).version).toBe(CAMPAIGN_SCHEMA_VERSION + 4);
    }
  });
});
